# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alexandru Topliceanu
tagline:          on software development
url:              http://alexandrutopliceanu.ro
paginate:         1
baseurl:          /
author:
  name:           Alexandru Topliceanu
  url:            http://alexandrutopliceanu.ro
  email:          alexandru.topliceanu@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
